# Generated by Django 2.2.4 on 2019-08-13 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estrutura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estrutura.Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('informacoes', models.TextField(verbose_name='informações')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do atendimento')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do fechamento')),
                ('status', django_fsm.FSMField(choices=[('aberto', 'Aberto'), ('duplicado', 'Duplicado'), ('atendendo', 'Atendendo'), ('em_espera', 'Em espera'), ('fechado', 'Fechado')], default='aberto', max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suporte.Categoria')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estrutura.Setor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_atender', 'Pode atender chamados'),),
            },
        ),
    ]
