# Generated by Django 2.2.3 on 2019-08-09 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'permissions': (('can_atender', 'Pode atender chamados'),)},
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_atendimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do atendimento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
