# Generated by Django 2.2.4 on 2019-09-03 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de abertura'),
            preserve_default=False,
        ),
    ]
