# Generated by Django 2.2.4 on 2019-09-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0002_chamado_data_abertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='relacionado',
            field=models.ForeignKey(blank=True, help_text='Informe o chamado caso exista relação com outro já informado ou se trate de um chamado duplicado', null=True, on_delete=django.db.models.deletion.PROTECT, to='suporte.Chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_atendimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de atendimento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de fechamento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=django_fsm.FSMField(choices=[('rascunho', 'Rascunho'), ('aberto', 'Aberto'), ('duplicado', 'Duplicado'), ('atendendo', 'Atendendo'), ('em_espera', 'Em espera'), ('fechado', 'Fechado')], default='rascunho', max_length=50),
        ),
    ]
