# Generated by Django 2.2.4 on 2019-09-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0003_auto_20190904_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de abertura'),
        ),
    ]
