# Generated by Django 2.2.4 on 2019-09-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0006_auto_20190905_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'comentário'},
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='mensagem',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(upload_to='suporte'),
        ),
    ]
