# Generated by Django 2.2.3 on 2019-07-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransAlunoPresenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenca_anterior', to='academico.Presenca')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Presenca')),
            ],
            options={
                'abstract': False,
                'unique_together': {('aluno', 'data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='TransAlunoNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_anterior', to='academico.Nota')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Nota')),
            ],
            options={
                'abstract': False,
                'unique_together': {('aluno', 'data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='TransAlunoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_anterior', to='academico.Matricula')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Matricula')),
            ],
            options={
                'abstract': False,
                'unique_together': {('aluno', 'data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='TransAlunoFinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeira_anterior', to='academico.Financeira')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Financeira')),
            ],
            options={
                'abstract': False,
                'unique_together': {('aluno', 'data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='TempoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
                ('andamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Andamento')),
                ('cadastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Cadastral', verbose_name='situação')),
                ('documentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Documentacao', verbose_name='documentação')),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Financeira')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Matricula', verbose_name='matrícula')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Nota')),
                ('presenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Presenca', verbose_name='presença')),
            ],
            options={
                'abstract': False,
                'unique_together': {('aluno', 'data', 'hora')},
            },
        ),
    ]
