# Generated by Django 2.2.4 on 2019-08-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0002_auto_20190826_1234'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransInscritoCadastral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadastral_anterior', to='ingresso.SitCadastral')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.Inscrito')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.SitCadastral')),
            ],
            options={
                'abstract': False,
                'unique_together': {('inscrito', 'data', 'hora')},
            },
        ),
    ]
