# Generated by Django 2.2.3 on 2019-07-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('relacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transalunopresenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunopresenca',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenca_anterior', to='relacionamento.Presenca'),
        ),
        migrations.AddField(
            model_name='transalunopresenca',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Presenca'),
        ),
        migrations.AddField(
            model_name='transalunonota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunonota',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_anterior', to='relacionamento.Nota'),
        ),
        migrations.AddField(
            model_name='transalunonota',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Nota'),
        ),
        migrations.AddField(
            model_name='transalunomatricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunomatricula',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_anterior', to='relacionamento.Matricula'),
        ),
        migrations.AddField(
            model_name='transalunomatricula',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Matricula'),
        ),
        migrations.AddField(
            model_name='transalunofinanceira',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunofinanceira',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeira_anterior', to='relacionamento.Financeira'),
        ),
        migrations.AddField(
            model_name='transalunofinanceira',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Financeira'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='andamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Andamento'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Cadastral', verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='documentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Documentacao', verbose_name='documentação'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='financeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Financeira'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Matricula', verbose_name='matrícula'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Nota'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='presenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Presenca', verbose_name='presença'),
        ),
        migrations.AlterUniqueTogether(
            name='transalunopresenca',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunonota',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunomatricula',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunofinanceira',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='tempoaluno',
            unique_together={('aluno', 'data', 'hora')},
        ),
    ]
