# Generated by Django 2.2.4 on 2019-11-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('captacao', '0002_auto_20190903_1323'),
        ('ingresso', '0001_initial'),
        ('permanencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transalunopresenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunopresenca',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenca_anterior', to='permanencia.SitPresenca'),
        ),
        migrations.AddField(
            model_name='transalunopresenca',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitPresenca'),
        ),
        migrations.AddField(
            model_name='transalunonota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunonota',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_anterior', to='permanencia.SitNota'),
        ),
        migrations.AddField(
            model_name='transalunonota',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitNota'),
        ),
        migrations.AddField(
            model_name='transalunomatricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunomatricula',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_anterior', to='permanencia.SitMatricula'),
        ),
        migrations.AddField(
            model_name='transalunomatricula',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitMatricula'),
        ),
        migrations.AddField(
            model_name='transalunofinanceira',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunofinanceira',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeira_anterior', to='permanencia.SitFinanceira'),
        ),
        migrations.AddField(
            model_name='transalunofinanceira',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitFinanceira'),
        ),
        migrations.AddField(
            model_name='transalunodocumentacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunodocumentacao',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentacao_anterior', to='permanencia.SitDocumentacao'),
        ),
        migrations.AddField(
            model_name='transalunodocumentacao',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitDocumentacao'),
        ),
        migrations.AddField(
            model_name='transalunocadastral',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunocadastral',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadastral_anterior', to='permanencia.SitCadastral'),
        ),
        migrations.AddField(
            model_name='transalunocadastral',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitCadastral'),
        ),
        migrations.AddField(
            model_name='transalunoandamento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.Aluno'),
        ),
        migrations.AddField(
            model_name='transalunoandamento',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andamento_anterior', to='permanencia.SitAndamento'),
        ),
        migrations.AddField(
            model_name='transalunoandamento',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitAndamento'),
        ),
        migrations.AddField(
            model_name='tempoinscrito',
            name='cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitCadastral', verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='tempoinscrito',
            name='inscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.Inscrito'),
        ),
        migrations.AddField(
            model_name='tempocontato',
            name='cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitCadastral', verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='tempocontato',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Contato'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.Aluno'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='andamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitAndamento'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitCadastral', verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='documentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitDocumentacao', verbose_name='documentação'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='financeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitFinanceira'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitMatricula', verbose_name='matrícula'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitNota'),
        ),
        migrations.AddField(
            model_name='tempoaluno',
            name='presenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permanencia.SitPresenca', verbose_name='presença'),
        ),
        migrations.AlterUniqueTogether(
            name='transinscritocadastral',
            unique_together={('inscrito', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transcontatocadastral',
            unique_together={('contato', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunopresenca',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunonota',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunomatricula',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunofinanceira',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunodocumentacao',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunocadastral',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunoandamento',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='tempoinscrito',
            unique_together={('inscrito', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='tempocontato',
            unique_together={('contato', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='tempoaluno',
            unique_together={('aluno', 'data', 'hora')},
        ),
    ]
