# Generated by Django 2.2.3 on 2019-07-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20190711_1054'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempoaluno',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunofinanceira',
            name='anterior',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeira_anterior', to='academico.Financeira'),
        ),
        migrations.AlterField(
            model_name='transalunofinanceira',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='TransAlunoPresenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
                ('anterior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenca_anterior', to='academico.Presenca')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Presenca')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransAlunoNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
                ('anterior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_anterior', to='academico.Nota')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Nota')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransAlunoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
                ('anterior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_anterior', to='academico.Matricula')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Matricula')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
