# Generated by Django 2.2.3 on 2019-07-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20190711_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transalunofinanceira',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeira_anterior', to='academico.Financeira'),
        ),
        migrations.AlterField(
            model_name='transalunomatricula',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_anterior', to='academico.Matricula'),
        ),
        migrations.AlterField(
            model_name='transalunonota',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_anterior', to='academico.Nota'),
        ),
        migrations.AlterField(
            model_name='transalunopresenca',
            name='anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenca_anterior', to='academico.Presenca'),
        ),
    ]
