# Generated by Django 2.2.4 on 2019-08-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0002_auto_20190826_1234'),
        ('relacionamento', '0001_initial'),
        ('log', '0002_transinscritocadastral'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempoInscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('cadastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.SitCadastral', verbose_name='situação')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.Inscrito')),
            ],
            options={
                'abstract': False,
                'unique_together': {('inscrito', 'data', 'hora')},
            },
        ),
    ]
