# Generated by Django 2.2.3 on 2019-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20190711_1054'),
        ('log', '0003_auto_20190711_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempoaluno',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunofinanceira',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunomatricula',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunonota',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunopresenca',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='tempoaluno',
            unique_together={('aluno', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunofinanceira',
            unique_together={('aluno', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunomatricula',
            unique_together={('aluno', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunonota',
            unique_together={('aluno', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunopresenca',
            unique_together={('aluno', 'data')},
        ),
    ]
