# Generated by Django 2.2.3 on 2019-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20190711_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempoaluno',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunofinanceira',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunomatricula',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunonota',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunopresenca',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
