# Generated by Django 2.2.3 on 2019-07-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20190711_1641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempoaluno',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transalunofinanceira',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transalunomatricula',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transalunonota',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transalunopresenca',
            unique_together=set(),
        ),
    ]
