# Generated by Django 2.2.3 on 2019-07-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20190711_1054'),
        ('log', '0010_auto_20190714_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempoaluno',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transalunofinanceira',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transalunomatricula',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transalunonota',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transalunopresenca',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='tempoaluno',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunofinanceira',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunomatricula',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunonota',
            unique_together={('aluno', 'data', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='transalunopresenca',
            unique_together={('aluno', 'data', 'hora')},
        ),
    ]
