# Generated by Django 2.2.3 on 2019-07-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20190714_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempoaluno',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tempoaluno',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transalunofinanceira',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunofinanceira',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transalunomatricula',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunomatricula',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transalunonota',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunonota',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transalunopresenca',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transalunopresenca',
            name='hora',
            field=models.TimeField(),
        ),
    ]
