# Generated by Django 2.2.3 on 2019-07-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoacao',
            old_name='leads',
            new_name='contatos',
        ),
    ]
