# Generated by Django 2.2.3 on 2019-07-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoacao',
            old_name='candidatos',
            new_name='inscritos',
        ),
    ]
