# Generated by Django 2.2.3 on 2019-07-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cadastral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'cadastrais',
            },
        ),
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'documentação',
                'verbose_name_plural': 'documentação',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'matrícula',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'presença',
            },
        ),
        migrations.CreateModel(
            name='Financeira',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('reversivel', models.BooleanField(default=False, verbose_name='reversível')),
                ('reversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Financeira', verbose_name='reversão')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=20, verbose_name='RA')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('curso', models.CharField(max_length=255)),
                ('curriculo', models.CharField(max_length=40, verbose_name='currículo')),
                ('serie', models.IntegerField(verbose_name='série')),
                ('polo', models.CharField(max_length=255)),
                ('andamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Andamento')),
                ('cadastral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Cadastral', verbose_name='situação')),
                ('documentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Documentacao', verbose_name='documentação')),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Financeira')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Matricula', verbose_name='matrícula')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Nota')),
                ('presenca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Presenca', verbose_name='presença')),
            ],
        ),
    ]
