# Generated by Django 2.2.3 on 2019-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RA'),
        ),
    ]
