# Generated by Django 2.2.3 on 2019-07-11 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento',
            name='reversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Andamento', verbose_name='reversão'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='reversivel',
            field=models.BooleanField(default=False, verbose_name='reversível'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='reversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Atividade', verbose_name='reversão'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='reversivel',
            field=models.BooleanField(default=False, verbose_name='reversível'),
        ),
        migrations.AddField(
            model_name='cadastral',
            name='reversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Cadastral', verbose_name='reversão'),
        ),
        migrations.AddField(
            model_name='cadastral',
            name='reversivel',
            field=models.BooleanField(default=False, verbose_name='reversível'),
        ),
        migrations.AddField(
            model_name='documentacao',
            name='reversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Documentacao', verbose_name='reversão'),
        ),
        migrations.AddField(
            model_name='documentacao',
            name='reversivel',
            field=models.BooleanField(default=False, verbose_name='reversível'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='reversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Matricula', verbose_name='reversão'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='reversivel',
            field=models.BooleanField(default=False, verbose_name='reversível'),
        ),
        migrations.AddField(
            model_name='nota',
            name='reversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Nota', verbose_name='reversão'),
        ),
        migrations.AddField(
            model_name='nota',
            name='reversivel',
            field=models.BooleanField(default=False, verbose_name='reversível'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='reversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Presenca', verbose_name='reversão'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='reversivel',
            field=models.BooleanField(default=False, verbose_name='reversível'),
        ),
    ]
