# Generated by Django 2.2.3 on 2019-07-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
        ),
        migrations.RenameModel(
            old_name='Situacao',
            new_name='Cadastral',
        ),
        migrations.RenameModel(
            old_name='Desempenho',
            new_name='Nota',
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={},
        ),
        migrations.AlterModelOptions(
            name='presenca',
            options={'verbose_name': 'presença'},
        ),
    ]
