# Generated by Django 2.2.3 on 2019-07-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_auto_20190702_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='reversao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Financeiro', verbose_name='reversão'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='reversivel',
            field=models.BooleanField(default=False, verbose_name='reversível'),
        ),
    ]
