# Generated by Django 2.2.3 on 2019-07-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_auto_20190710_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RA'),
        ),
    ]
