# Generated by Django 2.2.3 on 2019-07-04 14:22

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('academico', '0002_auto_20190704_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financeiro',
            new_name='Financeira',
        ),
        migrations.AlterModelOptions(
            name='andamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cadastral',
            options={'verbose_name_plural': 'cadastrais'},
        ),
        migrations.AlterModelOptions(
            name='documentacao',
            options={'verbose_name': 'documentação', 'verbose_name_plural': 'documentação'},
        ),
        migrations.AlterModelOptions(
            name='financeira',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'matrícula'},
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='situacao',
            new_name='cadastral',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='financeiro',
            new_name='financeira',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='desempenho',
            new_name='nota',
        ),
    ]
