# Generated by Django 2.2.3 on 2019-07-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20190710_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamento',
            name='reversao',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='reversivel',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='reversao',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='reversivel',
        ),
        migrations.RemoveField(
            model_name='cadastral',
            name='reversao',
        ),
        migrations.RemoveField(
            model_name='cadastral',
            name='reversivel',
        ),
        migrations.RemoveField(
            model_name='documentacao',
            name='reversao',
        ),
        migrations.RemoveField(
            model_name='documentacao',
            name='reversivel',
        ),
        migrations.RemoveField(
            model_name='financeira',
            name='reversao',
        ),
        migrations.RemoveField(
            model_name='financeira',
            name='reversivel',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='reversao',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='reversivel',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='reversao',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='reversivel',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='reversao',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='reversivel',
        ),
        migrations.AddField(
            model_name='andamento',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Andamento', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='conversivel',
            field=models.BooleanField(default=False, verbose_name='conversível'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Atividade', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='conversivel',
            field=models.BooleanField(default=False, verbose_name='conversível'),
        ),
        migrations.AddField(
            model_name='cadastral',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Cadastral', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='cadastral',
            name='conversivel',
            field=models.BooleanField(default=False, verbose_name='conversível'),
        ),
        migrations.AddField(
            model_name='documentacao',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Documentacao', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='documentacao',
            name='conversivel',
            field=models.BooleanField(default=False, verbose_name='conversível'),
        ),
        migrations.AddField(
            model_name='financeira',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Financeira', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='financeira',
            name='conversivel',
            field=models.BooleanField(default=False, verbose_name='conversível'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Matricula', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='conversivel',
            field=models.BooleanField(default=False, verbose_name='conversível'),
        ),
        migrations.AddField(
            model_name='nota',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Nota', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='nota',
            name='conversivel',
            field=models.BooleanField(default=False, verbose_name='conversível'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Presenca', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='conversivel',
            field=models.BooleanField(default=False, verbose_name='conversível'),
        ),
    ]
