# Generated by Django 2.2.3 on 2019-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20190704_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='cadastral',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='cadastral',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='documentacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='documentacao',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='financeira',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='financeira',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='situacao',
        ),
        migrations.AlterField(
            model_name='andamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cadastral',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financeira',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
