# Generated by Django 2.2.3 on 2019-07-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20190703_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='reversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Financeiro', verbose_name='reversão'),
        ),
    ]
