# Generated by Django 2.2.3 on 2019-07-16 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0003_auto_20190715_2225'),
        ('academico', '0004_auto_20190711_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('relacionamento.acao',),
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('obs', models.TextField(blank=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Acao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno')),
            ],
            options={
                'verbose_name': 'atendimento',
            },
        ),
    ]
