# Generated by Django 2.2.3 on 2019-07-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20190704_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='andamento',
            options={'verbose_name': 'situação', 'verbose_name_plural': 'situações'},
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name': 'situação', 'verbose_name_plural': 'situações'},
        ),
        migrations.AlterModelOptions(
            name='financeira',
            options={'verbose_name': 'situação', 'verbose_name_plural': 'situações'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'situação', 'verbose_name_plural': 'situações'},
        ),
        migrations.AddField(
            model_name='andamento',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='situacao',
            field=models.CharField(default=1, max_length=40, verbose_name='situação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='situacao',
            field=models.CharField(default=1, max_length=40, verbose_name='situação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastral',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='cadastral',
            name='situacao',
            field=models.CharField(default=1, max_length=40, verbose_name='situação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentacao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='documentacao',
            name='situacao',
            field=models.CharField(default=1, max_length=40, verbose_name='situação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeira',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='financeira',
            name='situacao',
            field=models.CharField(default=1, max_length=40, verbose_name='situação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='situacao',
            field=models.CharField(default=1, max_length=40, verbose_name='situação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='nota',
            name='situacao',
            field=models.CharField(default=1, max_length=40, verbose_name='situação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='andamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cadastral',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentacao',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='financeira',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
