# Generated by Django 2.2.3 on 2019-07-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_acao_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
