# Generated by Django 2.2.3 on 2019-07-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20190704_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='andamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='financeira',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={},
        ),
    ]
