# Generated by Django 2.2.3 on 2019-07-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingresso.Cadastral', verbose_name='conversão')),
            ],
            options={
                'verbose_name_plural': 'cadastrais',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='código')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('concurso', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('polo', models.CharField(max_length=255)),
                ('ano', models.CharField(max_length=4)),
                ('periodo', models.CharField(max_length=2)),
                ('cadastral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingresso.Cadastral', verbose_name='situação')),
            ],
        ),
    ]
