# Generated by Django 2.2.4 on 2019-08-26 12:34

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('ingresso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastral',
            new_name='SitCadastral',
        ),
    ]
