# Generated by Django 2.2.3 on 2019-07-22 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='atualização'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criação'),
            preserve_default=False,
        ),
    ]
