# Generated by Django 2.2.3 on 2019-08-05 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingresso', '0001_squashed_0003_auto_20190729_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'default_related_name': 'inscritos', 'verbose_name': 'atendimento'},
        ),
        migrations.AddField(
            model_name='atendimento',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inscritos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='inscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='ingresso.Inscrito'),
        ),
    ]
