# Generated by Django 2.2.3 on 2019-08-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
