# Generated by Django 2.2.3 on 2019-07-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
        ('ingresso', '0002_auto_20190722_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('acoes.acao',),
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='ingresso.Acao')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.Candidato')),
            ],
            options={
                'verbose_name': 'atendimento',
            },
        ),
    ]
