# Generated by Django 2.2.3 on 2019-07-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0002_auto_20190729_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingresso.Status'),
        ),
    ]
