# Generated by Django 2.2.3 on 2019-07-23 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('ingresso', '0003_acao_atendimento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidato',
            new_name='Inscrito',
        ),
        migrations.RenameField(
            model_name='atendimento',
            old_name='candidato',
            new_name='inscrito',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='ingresso.Acao'),
        ),
    ]
