# Generated by Django 2.2.3 on 2019-07-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0003_auto_20190722_2338'),
        ('ingresso', '0004_auto_20190723_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='captacao.Lead'),
        ),
    ]
