# Generated by Django 2.2.3 on 2019-07-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0005_inscrito_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='lead',
        ),
    ]
