# Generated by Django 2.2.3 on 2019-07-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0006_remove_inscrito_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name': 'ação', 'verbose_name_plural': 'ações'},
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='ingresso.Acao', verbose_name='ação'),
        ),
    ]
