# Generated by Django 2.2.4 on 2019-08-30 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('acoes', '0001_initial'),
        ('ingresso', '0002_auto_20190826_1234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('nao_ligar', models.BooleanField(default=False, verbose_name='não ligar')),
                ('em_atendimento', models.BooleanField(default=False, verbose_name='em atendimento')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='criação')),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'origens',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
            ],
            options={
                'verbose_name': 'ação',
                'verbose_name_plural': 'ações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('acoes.acao',),
        ),
        migrations.CreateModel(
            name='SitCadastral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='captacao.SitCadastral', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'sit. cadastral',
                'verbose_name_plural': 'sit. cadastrais',
            },
        ),
        migrations.CreateModel(
            name='Conversao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Acao', verbose_name='ação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Contato')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.Inscrito')),
            ],
            options={
                'verbose_name': 'conversão',
                'verbose_name_plural': 'conversões',
            },
        ),
        migrations.AddField(
            model_name='contato',
            name='cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.SitCadastral', verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='contato',
            name='inscricoes',
            field=models.ManyToManyField(through='captacao.Conversao', to='ingresso.Inscrito'),
        ),
        migrations.AddField(
            model_name='contato',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Origem'),
        ),
        migrations.AddField(
            model_name='contato',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='captacao.Status'),
        ),
        migrations.AddField(
            model_name='contato',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='AtendimentoAgendado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('realizado', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False, verbose_name='êxito')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_agendados', to='captacao.Acao', verbose_name='ação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Contato')),
            ],
            options={
                'verbose_name_plural': 'atendimentos agendados',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='captacao.Acao', verbose_name='ação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Contato')),
            ],
            options={
                'verbose_name': 'atendimento',
            },
        ),
    ]
