# Generated by Django 2.2.4 on 2019-09-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'atendimento',
            },
        ),
        migrations.CreateModel(
            name='AtendimentoAgendado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('realizado', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False, verbose_name='êxito')),
            ],
            options={
                'verbose_name_plural': 'atendimentos agendados',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='código')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('nao_ligar', models.BooleanField(default=False, verbose_name='não ligar')),
                ('em_atendimento', models.BooleanField(default=False, verbose_name='em atendimento')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='criação')),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'origens',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
            ],
            options={
                'verbose_name': 'ação',
                'verbose_name_plural': 'ações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('acoes.acao',),
        ),
        migrations.CreateModel(
            name='SitCadastral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='captacao.SitCadastral', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'sit. cadastral',
                'verbose_name_plural': 'sit. cadastrais',
            },
        ),
        migrations.CreateModel(
            name='Conversao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Acao', verbose_name='ação')),
            ],
            options={
                'verbose_name': 'conversão',
                'verbose_name_plural': 'conversões',
            },
        ),
    ]
