# Generated by Django 2.2.3 on 2019-07-29 22:16

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('captacao', '0001_initial'), ('captacao', '0002_auto_20190729_2023'), ('captacao', '0003_auto_20190729_2200')]

    initial = True

    dependencies = [
        ('acoes', '0001_initial'),
        ('ingresso', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='captacao.Cadastral', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'sit. cadastral',
                'verbose_name_plural': 'sit. cadastrais',
            },
        ),
        migrations.CreateModel(
            name='Conversao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conversão',
                'verbose_name_plural': 'conversões',
            },
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'origens',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
            ],
            options={
                'verbose_name': 'ação',
                'verbose_name_plural': 'ações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('acoes.acao',),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('nao_ligar', models.BooleanField(default=False, verbose_name='não ligar')),
                ('em_atendimento', models.BooleanField(default=False, verbose_name='em atendimento')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='criação')),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualização')),
                ('cadastral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Cadastral', verbose_name='situação')),
                ('inscricoes', models.ManyToManyField(through='captacao.Conversao', to='ingresso.Inscrito')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Origem')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='captacao.Status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='conversao',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Acao', verbose_name='ação'),
        ),
        migrations.AddField(
            model_name='conversao',
            name='inscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.Inscrito'),
        ),
        migrations.AddField(
            model_name='conversao',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Lead'),
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='captacao.Acao', verbose_name='ação')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Lead')),
            ],
            options={
                'verbose_name': 'atendimento',
            },
        ),
        migrations.CreateModel(
            name='ContatoAgendado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('realizado', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False, verbose_name='êxito')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos_agendados', to='captacao.Acao', verbose_name='ação')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Lead')),
            ],
            options={
                'verbose_name_plural': 'contatos agendados',
            },
        ),
    ]
