# Generated by Django 2.2.3 on 2019-07-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ingresso', '0001_squashed_0003_auto_20190729_2023'),
        ('captacao', '0001_squashed_0003_auto_20190729_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoAgendado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('realizado', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False, verbose_name='êxito')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_agendados', to='captacao.Acao', verbose_name='ação')),
            ],
            options={
                'verbose_name_plural': 'atendimentos agendados',
            },
        ),
        migrations.RenameField(
            model_name='atendimento',
            old_name='lead',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='conversao',
            old_name='lead',
            new_name='contato',
        ),
        migrations.RenameModel(
            old_name='Lead',
            new_name='Contato',
        ),
        migrations.DeleteModel(
            name='ContatoAgendado',
        ),
        migrations.AddField(
            model_name='atendimentoagendado',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Contato'),
        ),
    ]
