# Generated by Django 2.2.4 on 2019-08-13 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ingresso', '0001_initial'),
        ('captacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversao',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversao',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Contato'),
        ),
        migrations.AddField(
            model_name='conversao',
            name='inscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.Inscrito'),
        ),
        migrations.AddField(
            model_name='contato',
            name='cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Cadastral', verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='contato',
            name='inscricoes',
            field=models.ManyToManyField(through='captacao.Conversao', to='ingresso.Inscrito'),
        ),
        migrations.AddField(
            model_name='contato',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Origem'),
        ),
        migrations.AddField(
            model_name='contato',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='captacao.Status'),
        ),
        migrations.AddField(
            model_name='contato',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='cadastral',
            name='conversao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='captacao.Cadastral', verbose_name='conversão'),
        ),
        migrations.AddField(
            model_name='atendimentoagendado',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_agendados', to='captacao.Acao', verbose_name='ação'),
        ),
        migrations.AddField(
            model_name='atendimentoagendado',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimentoagendado',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Contato'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='captacao.Acao', verbose_name='ação'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Contato'),
        ),
    ]
