# Generated by Django 2.2.3 on 2019-07-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0002_auto_20190729_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='captacao.Acao', verbose_name='ação'),
        ),
        migrations.CreateModel(
            name='ContatoAgendado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('realizado', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False, verbose_name='êxito')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos_agendados', to='captacao.Acao', verbose_name='ação')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Lead')),
            ],
            options={
                'verbose_name_plural': 'contatos agendados',
            },
        ),
    ]
