# Generated by Django 2.2.3 on 2019-08-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0002_auto_20190806_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
