# Generated by Django 2.2.3 on 2019-07-23 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0006_remove_inscrito_lead'),
        ('captacao', '0003_auto_20190722_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='captacao.Acao'),
        ),
        migrations.CreateModel(
            name='Conversao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Acao')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.Inscrito')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.Lead')),
            ],
            options={
                'verbose_name': 'conversão',
                'verbose_name_plural': 'conversões',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='inscricoes',
            field=models.ManyToManyField(through='captacao.Conversao', to='ingresso.Inscrito'),
        ),
    ]
