# Generated by Django 2.2.3 on 2019-07-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0004_auto_20190723_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name': 'ação', 'verbose_name_plural': 'ações'},
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='naoligar',
            new_name='nao_ligar',
        ),
        migrations.AddField(
            model_name='lead',
            name='em_atendimento',
            field=models.BooleanField(default=False, verbose_name='em atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='captacao.Acao', verbose_name='ação'),
        ),
        migrations.AlterField(
            model_name='conversao',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.Acao', verbose_name='ação'),
        ),
    ]
