# Generated by Django 2.2.4 on 2019-08-13 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ra', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RA')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('curso', models.CharField(max_length=255)),
                ('curriculo', models.CharField(max_length=40, verbose_name='currículo')),
                ('serie', models.IntegerField(verbose_name='série')),
                ('polo', models.CharField(max_length=255)),
                ('obs', models.TextField(blank=True, null=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='criação')),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('acoes.acao',),
        ),
        migrations.CreateModel(
            name='SitPresenca',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitPresenca', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'presença',
            },
        ),
        migrations.CreateModel(
            name='SitNota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitNota', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'nota',
            },
        ),
        migrations.CreateModel(
            name='SitMatricula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitMatricula', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'matrícula',
            },
        ),
        migrations.CreateModel(
            name='SitFinanceira',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitFinanceira', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'finanaceira',
            },
        ),
        migrations.CreateModel(
            name='SitDocumentacao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitDocumentacao', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'documentação',
                'verbose_name_plural': 'documentação',
            },
        ),
        migrations.CreateModel(
            name='SitCadastral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitCadastral', verbose_name='conversão')),
            ],
            options={
                'verbose_name_plural': 'cadastrais',
            },
        ),
        migrations.CreateModel(
            name='SitAtividade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitAtividade', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'atividade',
            },
        ),
        migrations.CreateModel(
            name='SitAndamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=40, verbose_name='situação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conversivel', models.BooleanField(default=False, verbose_name='conversível')),
                ('conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitAndamento', verbose_name='conversão')),
            ],
            options={
                'verbose_name': 'andamento',
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobranca', models.IntegerField(unique=True)),
                ('tipo', models.CharField(max_length=20)),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4)),
                ('mes', models.DecimalField(decimal_places=0, max_digits=2)),
                ('data_venc', models.DateField(verbose_name='data de venc.')),
                ('data_pgto', models.DateField(blank=True, null=True, verbose_name='data de pgto.')),
                ('val_orig', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='val. orig.')),
                ('val_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='val. final')),
                ('val_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='val. pago')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='relacionamento.Acao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='relacionamento.Aluno')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atendimento',
                'default_related_name': 'alunos',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='andamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitAndamento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitCadastral', verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='documentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitDocumentacao', verbose_name='documentação'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='financeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitFinanceira'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitMatricula', verbose_name='matrícula'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitNota'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='presenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionamento.SitPresenca', verbose_name='presença'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relacionamento.Status'),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4)),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=2)),
                ('serie', models.IntegerField(verbose_name='série')),
                ('media', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='média')),
                ('media_min', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='média min.')),
                ('media_max', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='média máx.')),
                ('situacao', models.CharField(max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno')),
            ],
            options={
                'unique_together': {('disciplina', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4)),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=2)),
                ('data_entrega', models.DateTimeField(verbose_name='data da entrega')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nota_max', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nota máx.')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno')),
            ],
            options={
                'unique_together': {('disciplina', 'aluno', 'ano', 'periodo', 'sigla')},
            },
        ),
    ]
