# Generated by Django 2.2.3 on 2019-07-22 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='atualização'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='relacionamento.Acao'),
        ),
    ]
