# Generated by Django 2.2.3 on 2019-07-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentoaluno',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='atendimentoaluno',
            name='aluno',
        ),
        migrations.DeleteModel(
            name='AcaoAluno',
        ),
        migrations.AlterModelOptions(
            name='tipoacao',
            options={'verbose_name': 'tipo de ação', 'verbose_name_plural': 'tipos de ações'},
        ),
        migrations.DeleteModel(
            name='AtendimentoAluno',
        ),
    ]
