# Generated by Django 2.2.3 on 2019-07-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0001_squashed_0004_auto_20190729_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionamento.Cadastral', verbose_name='situação'),
        ),
    ]
