# Generated by Django 2.2.4 on 2019-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('log', '0001_initial'),
        ('relacionamento', '0002_cobranca_disciplina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Andamento',
            new_name='SitAndamento',
        ),
        migrations.RenameModel(
            old_name='Atividade',
            new_name='SitAtividade',
        ),
        migrations.RenameModel(
            old_name='Cadastral',
            new_name='SitCadastral',
        ),
        migrations.RenameModel(
            old_name='Documentacao',
            new_name='SitDocumentacao',
        ),
        migrations.RenameModel(
            old_name='Financeira',
            new_name='SitFinanceira',
        ),
        migrations.RenameModel(
            old_name='Matricula',
            new_name='SitMatricula',
        ),
        migrations.RenameModel(
            old_name='Nota',
            new_name='SitNota',
        ),
        migrations.RenameModel(
            old_name='Presenca',
            new_name='SitPresenca',
        ),
        migrations.AlterModelOptions(
            name='sitatividade',
            options={'verbose_name': 'atividade'},
        ),
        migrations.AlterModelOptions(
            name='sitfinanceira',
            options={'verbose_name': 'finanaceira'},
        ),
        migrations.AlterModelOptions(
            name='sitnota',
            options={'verbose_name': 'nota'},
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='nota',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='media',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='média'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='media_max',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=3, verbose_name='média máx.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='media_min',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=3, verbose_name='média min.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='serie',
            field=models.IntegerField(default=1, verbose_name='série'),
            preserve_default=False,
        ),
    ]
