# Generated by Django 2.2.3 on 2019-07-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0002_auto_20190715_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentoaluno',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='atendimentoaluno',
            name='aluno',
        ),
        migrations.DeleteModel(
            name='AcaoAluno',
        ),
        migrations.DeleteModel(
            name='AtendimentoAluno',
        ),
    ]
