# Generated by Django 2.2.4 on 2019-08-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0003_auto_20190813_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitandamento',
            options={'verbose_name': 'andamento'},
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.IntegerField()),
                ('sigla', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4)),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=2)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nota_min', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nota min.')),
                ('nota_max', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nota máx.')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.Aluno')),
            ],
            options={
                'unique_together': {('disciplina', 'aluno', 'ano', 'periodo', 'sigla')},
            },
        ),
    ]
